### ISSUE TITLE
nice works!

### ISSUE THREAD

**Issue by fjptscottliu** [MiracleDance/PoseRAC#1]
I wonder  if there are skeleton annotations used in this repo?

**Comment by MiracleDance** [comment]
Thanks for your issue! 

In our work, we directly use the BlazePose to estimate the pose key points, and it does not need fine-tune, so we do not need to annotate skeletons. 

Or it can be explained that the skeleton of each frame is directly estimated by BlazePose, and we use it directly.

**Comment by fjptscottliu** [comment]
Thankyou!

**Comment by fjptscottliu** [comment]
你好,请问
1.是否有all_action.csv文件
2.pose_train_all是否就是pose_train文件呢

**Comment by MiracleDance** [comment]
你好，
1. all_action.csv已经上传
2. 应该就是pose_train.csv文件，pose_train_all.csv是我在调试过程命名的，不过和pose_train.csv一样。可能我还没有清理好一些变量命名，抱歉！





发件人：fjptscottliu ***@***.***>
发送日期：2023-03-21 09:51:27
收件人：MiracleDance/PoseRAC ***@***.***>
抄送人：Ziyu Yao ***@***.***>,Comment ***@***.***>
主题：Re: [MiracleDance/PoseRAC] nice works! (Issue #1)

你好,请问
 1.是否有all_action.csv文件
 2.pose_train_all是否就是pose_train文件呢

**Comment by fjptscottliu** [comment]
谢谢你的解答,是我下载太早期版本了,已看到文件!
