### ISSUE TITLE
The self-training saved weights, i.e., the pth file cannot give the same results as the best_weights.pth 

### ISSUE THREAD

**Issue by DanielC-MST** [MiracleDance/PoseRAC#11]
I use the given weights best_weights_PoseRAC.pth and got MAE: 0.23, OBOA: 0.55
But when I trained on the dataset using the pre-trained.py and train.py and tested on the given data, the saved weights.pth file only yields MAE: 0.37 and OBOA: 0.43.

Do you happen to know the reason?
How did you obtain the "best_weights_PoseRAC.pth" ?

**Comment by Tungthanhlee** [comment]
The training process seems suspicious to me as well. The authors train and test on the same set (refer to line [94](https://github.com/MiracleDance/PoseRAC/blob/469590b611bde3595eaf163b517263da634e2096/train.py#L94C8-L94C8) in train.py)

**Comment by MiracleDance** [comment]
But the best results are still obtained by training with the provided code. Maybe you can try again?
