### ISSUE TITLE
如何获取npy

### ISSUE THREAD

**Issue by yuqilol** [MiracleDance/PoseRAC#12]
你好，我想用您的模型测试我自己的视频，但我不知道如何制作您的数据类型，主要卡在npy文件上，我不知道npy文件如何构成，如果可以透露，麻烦告知npy数据如何生成。

**Comment by MiracleDance** [comment]
你可以看一下pre_test.py，里面是npy数据的生成过程，概括说就是一个video的每一帧的landmarks（33*3=99个）
