### ISSUE TITLE
关于Transformer的输入

### ISSUE THREAD

**Issue by codeflysafe** [MiracleDance/PoseRAC#13]
很好的工作，请教一个关于Transformer输入的问题：
![image](https://github.com/MiracleDance/PoseRAC/assets/81274393/cd1561a6-1afc-47e2-b719-3e2f92aebefc)
文章中提到，输入到模型中的维度应该为 [k,b, d], b：为 batch size, k 为关键点的个数，及seq_len, d 即关键点的维度，文章中为3。但是在debug中发现， x = x.view(-1, 1, self.dim), dim = 99, 此时  b= 1, k = 16 (设定的batch_size), dim = 99。
![image](https://github.com/MiracleDance/PoseRAC/assets/81274393/8c8e9798-16bc-42ad-9079-730c5a64165f)
下文中提到的将关键点的个数dim (3) 升维的MLP在模型中我也没有找到
![image](https://github.com/MiracleDance/PoseRAC/assets/81274393/e28c5202-514d-4f45-a809-6f2b60e0f7a0)
请问我理解的是否有问题？非常感谢

**Comment by MiracleDance** [comment]
感谢关注，完整的实验过程是按照论文里的标准来执行的，但是开源的代码为了复现方便，做了一些细微地方的调整，并且发现调整之后的代码也可以达到几乎同样的性能（因为训练所需的数据很轻量，一些dimension和mlp的选择其实可以很灵活）
