### ISSUE TITLE
关于获取PoseRAC研究文件的请求

### ISSUE THREAD

**Issue by Wantong666** [MiracleDance/PoseRAC#14]
您好作者，关于您标注的关于PoseRAC: Pose Saliency Transformer for Repetitive Action Counting的UCFRep-pose的细粒度的annotations的标注文件，是否可以分享一下，十分感谢！

**Comment by Wantong666** [comment]
Hello, author, may I bother you? I am very interested in your research in this field. Here, I need classification and fine-grained annotations for the UCFRep dataset to obtain better validation results. If you could provide me with the relevant documents, I would greatly appreciate it. Thank you.

**Comment by MiracleDance** [comment]
please see issue#15
