### ISSUE TITLE
fine-grained annotations for the UCFRep dataset

### ISSUE THREAD

**Issue by Wantong666** [MiracleDance/PoseRAC#15]
Hello, author, may I bother you? I am very interested in your research in this field. Here, I need classification and fine-grained annotations for the UCFRep dataset to obtain better validation results. If you could provide me with the relevant documents, I would greatly appreciate it. Thank you.

**Comment by MiracleDance** [comment]
Maybe you need complete annotations for the whole UCFRep, but in this work, we only use 5 classes in UCFRep, and the annotations also only contain such 5 classes.

**Comment by Wantong666** [comment]
ok,thanks,i get it.
