### ISSUE TITLE
关于训练时的标签输入

### ISSUE THREAD

**Issue by Cecilia-yu412** [MiracleDance/PoseRAC#16]
在读取处理好的csv数据时，发现只对salient1的数据进行了读取，那么salient2帧对应的动作类标签不是全为0了吗？期待指点~
![微信图片_20231202150142](https://github.com/MiracleDance/PoseRAC/assets/64057508/70f04685-8df2-48ba-ba1a-f671f705e71a)

**Comment by fjptscottliu** [comment]
就是这样分类的,这是一个二分类问题,标签10分别对应一个关键帧,其他无关帧靠近中间值
