### ISSUE TITLE
作者能给个安装依赖项的requirements吗？

### ISSUE THREAD

**Issue by ibuen2000** [MiracleDance/PoseRAC#4]
可以给个requirements.txt吗？想知道具体版本号

**Comment by MiracleDance** [comment]
OK! requirements.txt has been updated. 

After some simple tests, most of the versions are bug-free (too old versions are not tested).

So don’t worry about the version number, just install them according to the latest versions.

**Comment by coralemon** [comment]
which is the version for torch and pytorch-lightning?

**Comment by MiracleDance** [comment]
> which is the version for torch and pytorch-lightning?

The most convenient way is to install the latest version of torch and pytorch-lightning directly, which is definitely no problem.

My environment is **torch1.13.1+cu117** and **pytorch_lightning2.0.1**. This might provide some reference.

**But it needs to be emphasized that a slightly lower version is also bug-free.**

**Comment by coralemon** [comment]
but I get error: 

TypeError:` __init__() got an unexpected keyword argument 'auto_lr_find'

and no .tune() for pytorch_lightning.

my version is pytorch_lightning2.0.1.

**Comment by ibuen2000** [comment]
> pytorch_lightning2.0.1

me too

**Comment by MiracleDance** [comment]
> but I get error:
> 
> TypeError:` **init**() got an unexpected keyword argument 'auto_lr_find'
> 
> and no .tune() for pytorch_lightning.
> 
> my version is pytorch_lightning2.0.1.

Emmmmm, strange

try **torch1.10.1+cu113** and **pytorch_lightning1.9.2** again?

**Comment by MiracleDance** [comment]
> > pytorch_lightning2.0.1
> 
> me too

try torch1.10.1+cu113 and pytorch_lightning1.9.2 again?

**Comment by coralemon** [comment]
I tried **torch'1.12.1+cu113' and pytorch_lightning1.9.5**,it works, thanks a lot.
And I check for the source code it seems pytorch_lightning2.0.1 indeed deletes  parameter auto_lr_find in Trainer class... orz

**Comment by MiracleDance** [comment]
OK, thanks for your suggestions, I will update the requirements.txt!
