### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ProvenceStar** [MiracleDance/PoseRAC#6]
I follow your guidance for preparation but found this problem:
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    main(args)
  File "train.py", line 93, in main
    train_landmarks, train_labels = csv2data(train_csv, action2index, num_classes)
  File "train.py", line 60, in csv2data
    train_landmarks, train_labels = obtain_landmark_label(train_csv, train_landmarks, train_labels, action2index, num_classes)
  File "train.py", line 49, in obtain_landmark_label
    start_str = row[0].split('/')[-3]
IndexError: list index out of range

Can you help me fix this problem?

**Comment by ProvenceStar** [comment]
In pdb I found that:
-> start_str = row[0].split('/')[-3]
(Pdb) row
['train\\bench_pressing\\salient1\\stu10_10.mp4\\0.jpg', 'bench_pressing', '389.7362', '139.97565', '113.36707', '398.86737', '146.87169', '114.61958', '399.11374', '148.47266', '114.58701', '399.35767', '150.18939', '114.57264', '397.9568', '145.32875', '131.86053', '397.6139', '145.84149', '131.81644', '397.32855', '146.41893', '131.81348', '394.9911', '160.26846', '111.81408', '393.32004', '156.35283', '190.98969', '382.79932', '143.81552', '110.438614', '381.6754', '141.53313', '133.18149', '368.03748', '170.49489', '44.945312', '331.77295', '153.34198', '224.38353', '372.0351', '110.72897', '-11.800899', '309.24008', '108.49926', '282.0064', '381.32538', '51.277473', '16.106916', '308.44193', '52.117702', '274.8035', '381.20837', '37.356636', '6.058373', '308.44168', '40.415825', '275.67664', '382.5362', '37.105045', '21.71938', '310.28625', '38.851154', '263.65643', '381.42633', '41.78264', '23.62736', '311.6772', '42.45645', '267.7368', '262.19678', '188.94446', '-43.46984', '237.76205', '182.55896', '43.168987', '182.01791', '237.34804', '-119.12424', '145.39159', '203.88889', '18.955482', '213.86421', '341.06656', '-78.240265', '163.47745', '286.01566', '56.04977', '226.5465', '346.2037', '-72.18167', '172.84271', '295.40082', '59.28237', '188.49487', '379.92758', '-95.65581', '136.9038', '312.74582', '28.670664']
(Pdb) row[0]'train\\bench_pressing\\salient1\\stu10_10.mp4\\0.jpg'
(Pdb) row[0].split('/')['train\\bench_pressing\\salient1\\stu10_10.mp4\\0.jpg']

Is this right?

**Comment by ProvenceStar** [comment]
if i change the code 'start_str = row[0].split('/')' into 'start_str = row[0].split('\\')', this line seems to work well, however another mistake interrupts:
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    main(args)
  File "train.py", line 94, in main
    train_landmarks, train_labels = csv2data(train_csv, action2index, num_classes)
  File "train.py", line 61, in csv2data
    train_landmarks, train_labels = obtain_landmark_label(train_csv, train_landmarks, train_labels, action2index, num_classes)
  File "train.py", line 51, in obtain_landmark_label
    label_np = np.zeros(num_classes)
AssertionError: Wrong number of values: 0
Could you please help me correct this mistake?

**Comment by MiracleDance** [comment]
> In pdb I found that: -> start_str = row[0].split('/')[-3] (Pdb) row ['train\bench_pressing\salient1\stu10_10.mp4\0.jpg', 'bench_pressing', '389.7362', '139.97565', '113.36707', '398.86737', '146.87169', '114.61958', '399.11374', '148.47266', '114.58701', '399.35767', '150.18939', '114.57264', '397.9568', '145.32875', '131.86053', '397.6139', '145.84149', '131.81644', '397.32855', '146.41893', '131.81348', '394.9911', '160.26846', '111.81408', '393.32004', '156.35283', '190.98969', '382.79932', '143.81552', '110.438614', '381.6754', '141.53313', '133.18149', '368.03748', '170.49489', '44.945312', '331.77295', '153.34198', '224.38353', '372.0351', '110.72897', '-11.800899', '309.24008', '108.49926', '282.0064', '381.32538', '51.277473', '16.106916', '308.44193', '52.117702', '274.8035', '381.20837', '37.356636', '6.058373', '308.44168', '40.415825', '275.67664', '382.5362', '37.105045', '21.71938', '310.28625', '38.851154', '263.65643', '381.42633', '41.78264', '23.62736', '311.6772', '42.45645', '267.7368', '262.19678', '188.94446', '-43.46984', '237.76205', '182.55896', '43.168987', '182.01791', '237.34804', '-119.12424', '145.39159', '203.88889', '18.955482', '213.86421', '341.06656', '-78.240265', '163.47745', '286.01566', '56.04977', '226.5465', '346.2037', '-72.18167', '172.84271', '295.40082', '59.28237', '188.49487', '379.92758', '-95.65581', '136.9038', '312.74582', '28.670664'] (Pdb) row[0]'train\bench_pressing\salient1\stu10_10.mp4\0.jpg' (Pdb) row[0].split('/')['train\bench_pressing\salient1\stu10_10.mp4\0.jpg']
> 
> Is this right?

Why your path is '...\\...\\...\\' ? With '\\' , of course it doesn't recognize '/' .

Maybe your environment is not under Linux? Better to replace it.

**Comment by ProvenceStar** [comment]
Thank you for your reply, the code is now working well!

**Comment by ProvenceStar** [comment]
> > In pdb I found that: -> start_str = row[0].split('/')[-3] (Pdb) row ['train\bench_pressing\salient1\stu10_10.mp4\0.jpg', 'bench_pressing', '389.7362', '139.97565', '113.36707', '398.86737', '146.87169', '114.61958', '399.11374', '148.47266', '114.58701', '399.35767', '150.18939', '114.57264', '397.9568', '145.32875', '131.86053', '397.6139', '145.84149', '131.81644', '397.32855', '146.41893', '131.81348', '394.9911', '160.26846', '111.81408', '393.32004', '156.35283', '190.98969', '382.79932', '143.81552', '110.438614', '381.6754', '141.53313', '133.18149', '368.03748', '170.49489', '44.945312', '331.77295', '153.34198', '224.38353', '372.0351', '110.72897', '-11.800899', '309.24008', '108.49926', '282.0064', '381.32538', '51.277473', '16.106916', '308.44193', '52.117702', '274.8035', '381.20837', '37.356636', '6.058373', '308.44168', '40.415825', '275.67664', '382.5362', '37.105045', '21.71938', '310.28625', '38.851154', '263.65643', '381.42633', '41.78264', '23.62736', '311.6772', '42.45645', '267.7368', '262.19678', '188.94446', '-43.46984', '237.76205', '182.55896', '43.168987', '182.01791', '237.34804', '-119.12424', '145.39159', '203.88889', '18.955482', '213.86421', '341.06656', '-78.240265', '163.47745', '286.01566', '56.04977', '226.5465', '346.2037', '-72.18167', '172.84271', '295.40082', '59.28237', '188.49487', '379.92758', '-95.65581', '136.9038', '312.74582', '28.670664'] (Pdb) row[0]'train\bench_pressing\salient1\stu10_10.mp4\0.jpg' (Pdb) row[0].split('/')['train\bench_pressing\salient1\stu10_10.mp4\0.jpg']
> > Is this right?
> 
> Why your path is '...\...\...\' ? With '\' , of course it doesn't recognize '/' .
> 
> Maybe your environment is not under Linux? Better to replace it.

Thank you for your reply, the code is now working well!

**Comment by MiracleDance** [comment]
Nice!
