### ISSUE TITLE
how to separate the Salient 1 and 2 and density level

### ISSUE THREAD

**Issue by DanielC-MST** [MiracleDance/PoseRAC#8]
Hi, Excellent Jog!

I would like to know since the training process learned features of both salient 1 and 2 together, why the visualization on the test dataset and the density map only obtained peaks at one salient action? How does the model differentiate salients 1 and 2? Or are there two parallel models, one for salient 1 and the other for salient 2?

**Comment by MiracleDance** [comment]
Maybe you can refer to Figure 5 in my paper. In Figure 5, there is an example:
![image](https://github.com/MiracleDance/PoseRAC/assets/123848076/3d9929c4-ae23-4879-8149-d739e8397071)

For the two salient poses of each action, we only use one Sigmoid value to represent, where 1 represents salient pose I and 0 represents salient pose II. 

We set upper and lower bounds to distinguish the scores of the two salient poses, which cluster non-salient poses in the middle and easily classify the salient poses to the two ends.

**Comment by DanielC-MST** [comment]
Thanks. Is that sigmoid designed in the layer after the density value of the continuous frames?

**Comment by MiracleDance** [comment]
Before and after are both ok, as long as we can get the classification of each frame.

**Comment by DanielC-MST** [comment]
Thanks.
