### ISSUE TITLE
Cannot replicate the results

### ISSUE THREAD

**Issue by wanghao-cst** [MiracleDance/PoseRAC#9]
Hello,

I recently downloaded and attempted to replicate the results of your open-source code. However, I'm facing challenges in achieving the reported accuracy as mentioned by the author in the documentation.

Here are the steps I followed:
step0: download the RepCount LLSP dataset
step1: generate pose for test set
         python pre_test.py --config ./RepCount_pose_config.yaml
step2: evaluate on the model you provided
         python eval.py --config ./RepCount_pose_config.yaml --ckpt ./best_weights_PoseRAC.pth
<img width="343" alt="image" src="https://github.com/MiracleDance/PoseRAC/assets/55015183/b1bd3b2c-55a4-48dd-b291-85ddbaf9b78c">
The MAE and OBO are 0.243 and 0.546 respectively.

Thank you for your attention to this matter. I look forward to your response.

**Comment by MiracleDance** [comment]
I try your steps again, but the results are still the same with that in README.md.
I'm not sure whether you have other different operations.
